version: "3.7"
services:

  backend:
    image: maven:3.3-jdk-8
    depends_on:
    - db
    ports:
      - "8080:8080"
    working_dir: /home/boot/app
    volumes:
    - ./register-system-backend:/home/boot/app
    command: "mvn spring-boot:run"
    
    
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - /docker-entrypoint-initdb.d:register-system-data
    environment:
      MYSQL_ROOT_PASSWORD: 
      
  frontend:
    image: node:13
    user: "node"
    working_dir: /home/node/app
    volumes:
    - ./register-system-admin:/home/node/app
    depends_on:
      - db
      - backend
    ports:
      - "3000:3000"
    command: "npm start"
    