version: "3.7"
services:

  backend:
    image: maven:3.3-jdk-8
    depends_on:
    - db
    ports:
      - "8080:8080"
    working_dir: /home/boot/app
    volumes:
    - ./register-system-backend:/home/boot/app
    command: "mvn spring-boot:run"
    
    
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./register-system-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      
  frontend:
    build: register-system-admin
    depends_on:
      - db
      - backend
    ports:
      - "3000:3000"
